export const Data=[
    
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQDp8YS-gvFNK2MEViDLS4q8CTB2gGT_JlFtw&usqp=CAU',
        name:'image1',
    },
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTB14xXOENU3scTyYWlYr6dkyQ-EXQafS0nbA&usqp=CAU',
        name:'image2',
    },
    {
        sourc:'https://archziner.com/wp-content/uploads/2020/08/drawing-of-tortoise-in-water-black-pencil-sketch-easy-animal-sketches-white-background.jpg',
        name:'image3',
    },
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQisunKcXiSID3QHG_cum2JhHpQh_kGY4duOQ&usqp=CAU',
        name:'image4',
    },
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRwztqwgEMyJ7ortiHkn0eJ6LPULdo9kutYYg&usqp=CAU',
        name:'image5',
    },
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQhe4SavLpwz5tg6mVG8MVopjuU2DV0Vu_FPw&usqp=CAU',
        name:'image6',
    },
    {
        sourc:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSA2eSDQx8CgGB9lO4-7I5eMVP0RS6LzymbGA&usqp=CAU',
        name:'image7',
    },
];